MyPersonalFinancesApp/Controllers/AccountSetupController.cs
using FinanceManager.Data;
using FinanceManager.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.CodeAnalysis.Options;
using Newtonsoft.Json.Linq;
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Model;

namespace FinanceManager.Controllers
{
    [Authorize]
    public class AccountSetupController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public AccountSetupController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAccountViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                var account = new Account
                {
                    Name = model.Name,
                    Currency = model.Currency,
                    InitialBalance = model.InitialBalance,
                    ApplicationUserId = userId,
                    IsActive = true
                };

                _context.Accounts.Add(account);
                await _context.SaveChangesAsync();

                // If the initial balance is greater than 0, create a corresponding income transaction.
                if (model.InitialBalance > 0)
                {
                    var initialBalanceCategory = await _context.Categories
                        .FirstOrDefaultAsync(c => c.ApplicationUserId == userId && c.Name == "Initial Balance");

                    if (initialBalanceCategory != null)
                    {
                        var initialIncome = new Income
                        {
                            Amount = model.InitialBalance,
                            Date = DateTime.Now,
                            Comment = "Initial account balance.",
                            AccountId = account.Id,
                            CategoryId = initialBalanceCategory.Id
                        };
                        _context.Transactions.Add(initialIncome);
                        await _context.SaveChangesAsync(); // Save the new transaction
                    }
                }

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }
    }
}

MyPersonalFinancesApp/Controllers/HomeController.cs
using FinanceManager.Data;
using FinanceManager.Models;
using FinanceManager.Models.Resources;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using System;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace FinanceManager.Controllers
{
    [Authorize] // Require user to be logged in to see the dashboard
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IStringLocalizer<Enums> _enumsLocalizer;

        public HomeController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IStringLocalizer<Enums> enumsLocalizer)
        {
            _context = context;
            _userManager = userManager;
            _enumsLocalizer = enumsLocalizer;
        }

        public async Task<IActionResult> Index(int? accountId, string selectedTimePeriod = "AllTime")
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userAccounts = await _context.Accounts
                .Where(a => a.ApplicationUserId == userId && a.IsActive)
                .ToListAsync();

            var timePeriodItems = Enum.GetValues<TimePeriod>()
        .Select(tp => new SelectListItem
        {
            Value = tp.ToString(),
            Text = _enumsLocalizer[$"TimePeriod_{tp.ToString()}"]
        }).ToList();

            var viewModel = new DashboardViewModel
            {
                SelectedAccountId = accountId,
                TimePeriods = new SelectList(timePeriodItems, "Value", "Text", selectedTimePeriod),
                SelectedTimePeriod = selectedTimePeriod
            };

            // --- CURRENT AMOUNT CALCULATION ---
            IQueryable<Transaction> balanceQuery = _context.Transactions.Where(t => t.Account.ApplicationUserId == userId);
            if (accountId.HasValue)
            {
                balanceQuery = balanceQuery.Where(t => t.AccountId == accountId.Value);
            }

            var totalIncome = await balanceQuery.OfType<Income>().SumAsync(i => (decimal?)i.Amount) ?? 0;
            var totalExpense = await balanceQuery.OfType<Expense>().SumAsync(e => (decimal?)e.Amount) ?? 0;
            viewModel.CurrentAmount = totalIncome - totalExpense;

            // --- CHART AND HISTORY QUERY ---
            IQueryable<Transaction> filteredQuery = _context.Transactions.Where(t => t.Account.ApplicationUserId == userId);
            if (accountId.HasValue)
            {
                filteredQuery = filteredQuery.Where(t => t.AccountId == accountId.Value);
            }

            Enum.TryParse<TimePeriod>(selectedTimePeriod, out var timePeriodEnum);
            DateTime startDate = DateTime.MinValue;
            switch (timePeriodEnum)
            {
                case TimePeriod.Day:
                    startDate = DateTime.Today;
                    break;
                case TimePeriod.Week:
                    startDate = DateTime.Today.AddDays(-6);
                    break;
                case TimePeriod.Month:
                    startDate = DateTime.Today.AddMonths(-1);
                    break;
                case TimePeriod.Year:
                    startDate = DateTime.Today.AddYears(-1);
                    break;
            }

            if (timePeriodEnum != TimePeriod.AllTime)
            {
                filteredQuery = filteredQuery.Where(t => t.Date >= startDate);
            }

            // Get Total Counts BEFORE taking the top 20
            viewModel.TotalIncomeCountForPeriod = await filteredQuery.OfType<Income>().CountAsync();
            viewModel.TotalExpenseCountForPeriod = await filteredQuery.OfType<Expense>().CountAsync();

            viewModel.RecentIncomes = await filteredQuery.OfType<Income>()
                .Include(i => i.Category)
                .Include(i => i.Account)
                .OrderByDescending(i => i.Date)
                .Take(20)
                .ToListAsync();

            viewModel.RecentExpenses = await filteredQuery.OfType<Expense>()
                .Include(e => e.Category)
                .Include(i => i.Account)
                .OrderByDescending(e => e.Date)
                .Take(20)
                .ToListAsync();

            var expenseData = await filteredQuery.OfType<Expense>()
                .Include(e => e.Category)
                .GroupBy(e => new { e.Category.Name, e.Category.Color })
                .Select(group => new { Category = group.Key.Name, Color = group.Key.Color, Total = group.Sum(e => e.Amount) })
                .OrderByDescending(x => x.Total)
                .ToListAsync();

            viewModel.ExpenseChartData.Labels = expenseData.Select(x => x.Category).ToList();
            viewModel.ExpenseChartData.Values = expenseData.Select(x => x.Total).ToList();
            viewModel.ExpenseChartData.Colors = expenseData.Select(x => x.Color).ToList();

            var incomeData = await filteredQuery.OfType<Income>()
                .Include(i => i.Category)
                .GroupBy(i => new { i.Category.Name, i.Category.Color })
                .Select(group => new { Category = group.Key.Name, Color = group.Key.Color, Total = group.Sum(i => i.Amount) })
                .OrderByDescending(x => x.Total)
                .ToListAsync();

            viewModel.IncomeChartData.Labels = incomeData.Select(x => x.Category).ToList();
            viewModel.IncomeChartData.Values = incomeData.Select(x => x.Total).ToList();
            viewModel.IncomeChartData.Colors = incomeData.Select(x => x.Color).ToList();

            return View(viewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        //[HttpPost]
        //public IActionResult SetCulture(string culture, string returnUrl)
        //{
        //    Response.Cookies.Append(
        //        CookieRequestCultureProvider.DefaultCookieName,
        //        CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
        //        new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
        //    );

        //    return LocalRedirect(returnUrl);
        //}
    }
}

MyPersonalFinancesApp/Controllers/TransactionController.cs
using FinanceManager.Data;
using FinanceManager.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace FinanceManager.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public TransactionController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string type)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["TransactionType"] = type;

            IQueryable<Transaction> query = _context.Transactions
                .Where(t => t.Account.ApplicationUserId == userId)
                .Include(t => t.Account)
                .Include(t => t.Category)
                .OrderByDescending(t => t.Date);

            if (type == "Income")
            {
                var model = await query.OfType<Income>().ToListAsync();
                return View(model);
            }
            else
            {
                var model = await query.OfType<Expense>().ToListAsync();
                return View(model);
            }
        }

        public async Task<IActionResult> Create(string type)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (string.IsNullOrEmpty(type) || (type != "Income" && type != "Expense"))
            {
                type = "Expense";
            }

            var viewModel = new TransactionCreateViewModel
            {
                TransactionType = type,
                Accounts = new SelectList(await _context.Accounts
                    .Where(a => a.ApplicationUserId == userId && a.IsActive)
                    .ToListAsync(), "Id", "Name"),
                ExpenseCategories = new SelectList(await _context.Categories
                    .Where(c => c.ApplicationUserId == userId && c.Type == CategoryType.Expense)
                    .ToListAsync(), "Id", "Name"),
                IncomeCategories = new SelectList(await _context.Categories
                    .Where(c => c.ApplicationUserId == userId && c.Type == CategoryType.Income)
                    .ToListAsync(), "Id", "Name")
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TransactionCreateViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (ModelState.IsValid)
            {
                Transaction transaction = model.TransactionType == "Income" ? new Income() : new Expense();

                transaction.Amount = model.Amount;
                transaction.AccountId = model.AccountId;
                transaction.CategoryId = model.CategoryId;
                transaction.Date = model.Date;
                transaction.Comment = model.Comment;

                if (!string.IsNullOrWhiteSpace(model.Tags))
                {
                    await ProcessTags(model.Tags, transaction, userId);
                }

                _context.Transactions.Add(transaction);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }

            // If model is invalid, re-populate the dropdowns before returning the view
            model.Accounts = new SelectList(await _context.Accounts
                .Where(a => a.ApplicationUserId == userId && a.IsActive)
                .ToListAsync(), "Id", "Name", model.AccountId);
            model.ExpenseCategories = new SelectList(await _context.Categories
                .Where(c => c.ApplicationUserId == userId && c.Type == CategoryType.Expense)
                .ToListAsync(), "Id", "Name", model.CategoryId);
            model.IncomeCategories = new SelectList(await _context.Categories
                .Where(c => c.ApplicationUserId == userId && c.Type == CategoryType.Income)
                .ToListAsync(), "Id", "Name", model.CategoryId);

            return View(model);
        }

        private async Task ProcessTags(string tags, Transaction transaction, string userId)
        {
            var tagNames = tags.Split(',').Select(t => t.Trim().ToLower()).Where(t => !string.IsNullOrEmpty(t));

            foreach (var tagName in tagNames)
            {
                var tag = await _context.Tags
                    .FirstOrDefaultAsync(t => t.Name.ToLower() == tagName && t.ApplicationUserId == userId);

                if (tag == null)
                {
                    tag = new Tag { Name = tagName, ApplicationUserId = userId };
                    _context.Tags.Add(tag);
                }

                transaction.TransactionTags.Add(new TransactionTag { Tag = tag });
            }
        }
    }
}

MyPersonalFinancesApp/Views/Home/Index.cshtml
@model FinanceManager.Models.DashboardViewModel
@using System.Text.Json
@using FinanceManager.Models.Resources

@inject IStringLocalizer<Homepage> HomepageLocalizer
@inject IStringLocalizer<SharedStrings> SharedLocalizer
@inject IStringLocalizer<CategoriesDefault> CategoryLocalizer

@{
    ViewData["Title"] = HomepageLocalizer["Dashboard"];

    string LocalizeCategory(string categoryName)
    {
        if (string.IsNullOrEmpty(categoryName)) { return ""; }
        var localized = CategoryLocalizer[categoryName.Replace(" ", "_")];
        return localized.ResourceNotFound ? categoryName : localized;
    }

    string FormatCurrency(decimal amount, Currency currency)
    {
        var symbol = currency switch { Currency.USD => "$", Currency.EUR => "€", Currency.UAH => "₴", _ => "" };
        return $"{symbol}{amount.ToString("N2", System.Globalization.CultureInfo.InvariantCulture)}";
    }
}

<!-- MASTER FILTER FORM -->
<form asp-action="Index" method="get" id="filterForm">
    <div class="row justify-content-center mb-4">
        <div class="col-md-4">
            <div class="input-group">
                <label class="input-group-text">@HomepageLocalizer["Account"]:</label>
                <select name="accountId" asp-for="SelectedAccountId" class="form-select" id="accountIdSelect">
                    <option value="">@HomepageLocalizer["GeneralAll"]</option>
                    @if (Model.Accounts != null)
                    {
                        @foreach (var account in Model.Accounts)
                        {
                            <option value="@account.Value">@account.Text</option>
                        }
                    }
                    <option disabled>------------------</option>
                    <option value="create_new">@HomepageLocalizer["CreateNewAcc"]</option>
                </select>
            </div>
        </div>
    </div>
    <div class="dashboard-box text-center mb-4">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h5 class="text-muted">@HomepageLocalizer["CurrentAmount"]</h5>
                <h2>@FormatCurrency(Model.CurrentAmount, Model.RecentExpenses.FirstOrDefault()?.Account.Currency ?? (Model.RecentIncomes.FirstOrDefault()?.Account.Currency ?? Currency.UAH))</h2>
            </div>
            <div class="col-md-4">
                <div class="input-group">
                    <label class="input-group-text">@HomepageLocalizer["Period"]:</label>
                    <select name="selectedTimePeriod" asp-for="SelectedTimePeriod" asp-items="Model.TimePeriods" class="form-select" id="timePeriodSelect"></select>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="row">
    <!-- WEST SIDE: Expenses -->
    <div class="col-md-6 mb-4">
        <div class="dashboard-box chart-box mb-3">
            <h3 class="text-center">@SharedLocalizer["Expenses"]</h3>
            <div class="pie-chart-container">
                <canvas id="expenseChart"></canvas>
            </div>
            <a asp-controller="Transaction" asp-action="Create" asp-route-type="Expense" class="create-transaction-btn">+</a>
        </div>
        <div class="dashboard-box">
            <h5 class="mt-1">@HomepageLocalizer["RecentExpenses"]</h5>
            <a asp-controller="Transaction" asp-action="Index" asp-route-type="Expense" class="stretched-link"></a>
            @if (Model.RecentExpenses.Any())
            {
                <ul class="list-group list-group-flush">
                    @foreach (var expense in Model.RecentExpenses)
                    {
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div><strong>@LocalizeCategory(expense.Category.Name)</strong><small class="d-block text-muted">@expense.Date.ToShortDateString()</small></div>
                            <span class="badge bg-danger rounded-pill">-@FormatCurrency(expense.Amount, expense.Account.Currency)</span>
                        </li>
                    }
                </ul>
            }
            else
            {
                <p class="text-center text-muted mt-3">@HomepageLocalizer["NoExpensesFound"]</p>
            }
            @if (Model.TotalExpenseCountForPeriod > 20)
            {
                <div class="text-center text-muted mt-2">
                    @HomepageLocalizer.GetString("AndMore", Model.TotalExpenseCountForPeriod - 20)
                </div>
            }
        </div>
    </div>

    <!-- EAST SIDE: Income -->
    <div class="col-md-6 mb-4">
        <div class="dashboard-box chart-box mb-3">
            <h3 class="text-center">@SharedLocalizer["Income"]</h3>
            <div class="pie-chart-container">
                <canvas id="incomeChart"></canvas>
            </div>
            <a asp-controller="Transaction" asp-action="Create" asp-route-type="Income" class="create-transaction-btn">+</a>
        </div>
        <div class="dashboard-box">
            <h5 class="mt-1">@HomepageLocalizer["RecentIncome"]</h5>
            <a asp-controller="Transaction" asp-action="Index" asp-route-type="Income" class="stretched-link"></a>
            @if (Model.RecentIncomes.Any())
            {
                <ul class="list-group list-group-flush">
                    @foreach (var income in Model.RecentIncomes)
                    {
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div><strong>@LocalizeCategory(income.Category.Name)</strong><small class="d-block text-muted">@income.Date.ToShortDateString()</small></div>
                            <span class="badge bg-success rounded-pill">+@FormatCurrency(income.Amount, income.Account.Currency)</span>
                        </li>
                    }
                </ul>
            }
            else
            {
                <p class="text-center text-muted mt-3">@HomepageLocalizer["NoIncomeFound"]</p>
            }
            @if (Model.TotalIncomeCountForPeriod > 20)
            {
                <div class="text-center text-muted mt-2">
                    @HomepageLocalizer.GetString("AndMore", Model.TotalIncomeCountForPeriod - 20)
                </div>
            }
        </div>
    </div>
</div>


@section Scripts {
    <script>
        // --- Reusable function for the placeholder chart ---
        function createPlaceholderChart(canvasId) {
            const canvas = document.getElementById(canvasId);
            if (!canvas) return;
            const ctx = canvas.getContext('2d');
            new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: ['No Data'],
                    datasets: [{
                        data: [1],
                        backgroundColor: ['#E9ECEF'],
                        borderWidth: 0
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: {
                        tooltip: { enabled: false },
                        legend: { display: false }
                    }
                }
            });
        }

        // --- CUSTOM CHART.JS PLUGIN to draw text in the center ---
        const doughnutCenterText = {
            id: 'doughnutCenterText',
            afterDraw: (chart) => {
                if (chart.options.plugins.doughnutCenterText.text) {
                    const ctx = chart.ctx;
                    const text = chart.options.plugins.doughnutCenterText.text;
                    const holeRadius = chart.innerRadius;
                    const maxTextWidth = (holeRadius * 2) - 20;

                    ctx.save();
                    ctx.font = 'bold 1.2em sans-serif';
                    ctx.textAlign = 'center';
                    ctx.textBaseline = 'middle';
                    ctx.fillStyle = '#6c757d';

                    let textToDraw = text;
                    if (ctx.measureText(textToDraw).width > maxTextWidth) {
                        while (ctx.measureText(textToDraw + '...').width > maxTextWidth && textToDraw.length > 0) {
                            textToDraw = textToDraw.slice(0, -1);
                        }
                        textToDraw += '...';
                    }

                    const x = (chart.chartArea.left + chart.chartArea.right) / 2;
                    const y = (chart.chartArea.top + chart.chartArea.bottom) / 2;
                    ctx.fillText(textToDraw, x, y);
                    ctx.restore();
                }
            }
        };

        // --- MAIN SCRIPT EXECUTION on page load ---
        document.addEventListener('DOMContentLoaded', function () {

            // --- FORM FILTER HANDLING ---
            const accountSelect = document.getElementById('accountIdSelect');
            const timePeriodSelect = document.getElementById('timePeriodSelect');
            const filterForm = document.getElementById('filterForm');

            if (accountSelect) {
                accountSelect.addEventListener('change', function() {
                    if (this.value === 'create_new') {
                        window.location.href = '@Url.Action("Create", "AccountSetup")';
                    } else {
                        filterForm.submit();
                    }
                });
            }
            if (timePeriodSelect) {
                timePeriodSelect.addEventListener('change', function() {
                    filterForm.submit();
                });
            }

            // --- CHART RENDERING ---
            const expenseData = @Html.Raw(JsonSerializer.Serialize(Model.ExpenseChartData));
            if (expenseData && expenseData.Values.length > 0) {
                const defaultExpenseText = expenseData.Labels[0];
                const expenseCtx = document.getElementById('expenseChart').getContext('2d');
                const expenseChart = new Chart(expenseCtx, {
                    type: 'doughnut',
                    plugins: [doughnutCenterText],
                    data: {
                        labels: expenseData.Labels,
                        datasets: [{
                            data: expenseData.Values,
                            backgroundColor: expenseData.Colors,
                            borderWidth: 2
                        }]
                    },
                    options: {
                        cutout: '70%',
                        maintainAspectRatio: false,
                        plugins: {
                            legend: { display: false },
                            doughnutCenterText: { text: defaultExpenseText }
                        },
                        onHover: (event, chartElement) => {
                            const activeElements = chartElement || [];
                            if (activeElements.length > 0) {
                                const index = activeElements[0].index;
                                const label = expenseChart.data.labels[index];
                                expenseChart.options.plugins.doughnutCenterText.text = label;
                            } else {
                                expenseChart.options.plugins.doughnutCenterText.text = defaultExpenseText;
                            }
                            expenseChart.update('none');
                        }
                    }
                });
            } else {
                createPlaceholderChart('expenseChart');
            }

            const incomeData = @Html.Raw(JsonSerializer.Serialize(Model.IncomeChartData));
            if (incomeData && incomeData.Values.length > 0) {
                const defaultIncomeText = incomeData.Labels[0];
                const incomeCtx = document.getElementById('incomeChart').getContext('2d');
                const incomeChart = new Chart(incomeCtx, {
                    type: 'doughnut',
                    plugins: [doughnutCenterText],
                    data: {
                        labels: incomeData.Labels,
                        datasets: [{
                            data: incomeData.Values,
                            backgroundColor: incomeData.Colors,
                            borderWidth: 2
                        }]
                    },
                    options: {
                        cutout: '70%',
                        maintainAspectRatio: false,
                        plugins: {
                            legend: { display: false },
                            doughnutCenterText: { text: defaultIncomeText }
                        },
                        onHover: (event, chartElement) => {
                            const activeElements = chartElement || [];
                            if (activeElements.length > 0) {
                                const index = activeElements[0].index;
                                const label = incomeChart.data.labels[index];
                                incomeChart.options.plugins.doughnutCenterText.text = label;
                            } else {
                                incomeChart.options.plugins.doughnutCenterText.text = defaultIncomeText;
                            }
                            incomeChart.update('none');
                        }
                    }
                });
            } else {
                createPlaceholderChart('incomeChart');
            }
        });
    </script>
}